### ISSUE TITLE
[Chore] Local setup failure

### ISSUE THREAD

**Issue by longnd** [aungkoko1234/web-scrapper-backend#14]
Issue
---
I followed the README file to set up the project on local that has the following instructions:
```
$ npm install
$ npm run start
```

but the first command fails with the following errors
![image](https://user-images.githubusercontent.com/1896814/210513342-fe6e12b2-fa80-43e0-bf7c-f2a5d4fe5be8.png)
I have nodeJS v16 on my local.

It turns out the project uses yarn as the package manager. I had to use it instead.

But then, I faced some other issues:
- there is no guidance on how to set the required environment variables.
https://github.com/aungkoko1234/web-scrapper-backend/blob/c4b47fd060b39a3c324e3d05d372760c366c3b80/src/config/configuration.ts#L3-L11
- I don't know how to run the migration for the database.

Usually the README should provide the complete guidance to setup the project on local, including the required dependencies. e.g. node version.
Ideally, the application should be Dockerized.

Expected
----
The application can be setup properly on local.

**Comment by aungkoko1234** [comment]
I will provide you en variables to set up. I am just about you to provide it read.me . But the deadline is over. That's why my bad.

**Comment by aungkoko1234** [comment]
I have resolved this issue by #17  pull request. Please kindly check it @longnd

**Comment by longnd** [comment]
it's clearer now. Thank you.
